
storage_directory_new: "/tmp/bridgingHub_example"
storage_directory_archive: ""
storage_directory_junk: ""
timestamp_name: "timestamp"
geohash_name: ""
value_register_map:
  0:
    id: 'test0'
    type: 'retval'
    unit: ''

