
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
ignore_missing_imports = true

[tool.black]
line-length = 79

[tool.flake8]
max-line-length = 79
extend-ignore = ["E203", "W503", "W504"]

[tool.isort]
profile = "black"

