name: Pre-commit checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: docker
    container: python:3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git curl

      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install-hooks

      - name: Run pre-commit checks
        run: pre-commit run --all-files

