
_bH:
  compat: 1.0
  #TODOextend_python_path: []

_data: "config/data.d/example/example.yml"


stdinput: "config/collect.d/example/example.yml"

tmpbuffer:
  module_type: "storage:buffer"
  module_path: "module.storage.default_storage"
  module_class_name: "DefaultStorageModule"
  buffer: "/tmp/bridgingHubTest/new"

stdoutput: "config/send.d/example/example.yml"

remember:
  module_type: "storage:archive"
  module_path: "module.storage.default_storage"
  module_class_name: "DefaultStorageModule"
  buffer: "/tmp/bridgingHubTest/new"
  junk: "/tmp/bridgingHubTest/junk"
  archive: "/tmp/bridgingHubTest/archive"

  #filter:
    #pre: # not implemented yet
    #main: # not implemented yet
    #post: # not implemented yet


